### ISSUE TITLE
It would be cool if we could tell if rotation was needed

### ISSUE THREAD

**Issue by jhihn** [vonheim/node-auto-rotate#2]
And have a configurable action if no rotation is needed. I'm not sure of what kind of CPU processing is done down the line. 

It would be cool if we could specify rotate(inFile, outFile, function noRotationHandler(), function RotationHandler() ... ) ;

So that we can collapse the no rotation scenario into a filesystem move (best case) or copy (any other case).

**Comment by vonheim** [comment]
Good idea. It now does a simple file copy if no rotation is needed, and the promise from autoRotateFile() returns a true value if the image was transformed (actually the LWIP image object).
Hope it solves your problem.
